In [1]:
import pandas as pd


INDEX_COL="ID"
LABEL = 'target'
PROJECT_NAME="santander"
INPUT_DIR="data/{}".format(PROJECT_NAME)
train_df = pd.read_csv("../{}/train.csv".format(INPUT_DIR))

In [2]:
train_df.head()

,ID,target,48df886f9,0deb4b6a8,34b15f335,a8cb14b00,2f0771a37,30347e683,d08d1fbe3,6ee66e115,...,3ecc09859,9281abeea,8675bec0b,3a13ed79a,f677d4d13,71b203550,137efaa80,fb36b89d9,7e293fbaf,9fc776466
0,000d6aaf2,38000000.0,0.0,0,0.0,0,0,0,0,0,...,0.0,0.0,0.0,0,0,0,0,0,0,0
1,000fbd867,600000.0,0.0,0,0.0,0,0,0,0,0,...,0.0,0.0,0.0,0,0,0,0,0,0,0
2,0027d6b71,10000000.0,0.0,0,0.0,0,0,0,0,0,...,0.0,0.0,0.0,0,0,0,0,0,0,0
3,0028cbf45,2000000.0,0.0,0,0.0,0,0,0,0,0,...,0.0,0.0,0.0,0,0,0,0,0,0,0
4,002a68644,14400000.0,0.0,0,0.0,0,0,0,0,0,...,0.0,0.0,0.0,0,0,0,0,0,0,0

In [3]:
cols = list(train_df)
features = [col for col in cols if col not in [INDEX_COL, LABEL]]

In [11]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

for i in range(5):
    print("Summary for '{}' column".format(features[i]))
    print(train_df[features[i]].describe())
    print("\n")

Summary for '48df886f9' column
count       4459.000
mean       14654.930
std       389329.809
min            0.000
25%            0.000
50%            0.000
75%            0.000
max     20000000.000
Name: 48df886f9, dtype: float64


Summary for '0deb4b6a8' column
count      4459.000
mean       1390.895
std       64283.024
min           0.000
25%           0.000
50%           0.000
75%           0.000
max     4000000.000
Name: 0deb4b6a8, dtype: float64


Summary for '34b15f335' column
count       4459.000
mean       26722.451
std       569965.183
min            0.000
25%            0.000
50%            0.000
75%            0.000
max     20000000.000
Name: 34b15f335, dtype: float64


Summary for 'a8cb14b00' column
count       4459.000
mean        4530.164
std       235912.407
min            0.000
25%            0.000
50%            0.000
75%            0.000
max     14800000.000
Name: a8cb14b00, dtype: float64


Summary for '2f0771a37' column
count        4459.000
mean        26409.957
std       1514730.151
min             0.000
25%             0.000
50%             0.000
75%             0.000
max     100000000.000
Name: 2f0771a37, dtype: float64